# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d40021fa7ae8d6fbbbfcc82821674fc82d69192e987378e881011d1e5bae7ff42ae7a0d75959a0316da200fdc28dfe41ae4905889599ed25de3a0fab729cb79d

test:
  secret_key_base: 0d25ff32e651eeadadc16a2e27d1283358317416df7bb30e0a81654355ffc3769d01e41bcd9552fd90ebe714782b56d9ace681360f9ee651c37533d2e9677bdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
